/* confdefs.h */
#define PACKAGE_NAME "LibreDWG"
#define PACKAGE_TARNAME "libredwg"
#define PACKAGE_VERSION "a0e31487-dirty"
#define PACKAGE_STRING "LibreDWG a0e31487-dirty"
#define PACKAGE_BUGREPORT "libredwg@gnu.org"
#define PACKAGE_URL "https://savannah.gnu.org/projects/libredwg/"
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define ENABLE_SHARED 1
#define restrict __restrict__
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STDDEF_H 1
#define HAVE_UNISTD_H 1
#define HAVE_MALLOC_H 1
#define HAVE_WCHAR_H 1
#define HAVE_CTYPE_H 1
#define HAVE_WCTYPE_H 1
#define HAVE_FLOAT_H 1
#define HAVE_LIMITS_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_LIBGEN_H 1
#define HAVE_ICONV_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_GETOPT_H 1
#define HAVE_ALLOCA_H 1
