/* confdefs.h */
#define PACKAGE_NAME "LibreDWG"
#define PACKAGE_TARNAME "libredwg"
#define PACKAGE_VERSION "fc3b1ce6-dirty"
#define PACKAGE_STRING "LibreDWG fc3b1ce6-dirty"
#define PACKAGE_BUGREPORT "libredwg@gnu.org"
#define PACKAGE_URL "https://savannah.gnu.org/projects/libredwg/"
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define ENABLE_SHARED 1
#define restrict __restrict__
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STDDEF_H 1
#define HAVE_UNISTD_H 1
#define HAVE_MALLOC_H 1
#define HAVE_WCHAR_H 1
#define HAVE_CTYPE_H 1
#define HAVE_WCTYPE_H 1
#define HAVE_FLOAT_H 1
#define HAVE_LIMITS_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_LIBGEN_H 1
#define HAVE_ICONV_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_GETOPT_H 1
#define HAVE_ALLOCA_H 1
#define HAVE_ENDIAN_H 1
#define HAVE_BYTESWAP_H 1
#define HAVE__BOOL 1
#define AX_STRCASECMP_HEADER <strings.h>
#define HAVE_LE16TOH 1
#define HAVE_LE32TOH 1
#define HAVE_LE64TOH 1
#define HAVE_HTOLE32 1
#define HAVE_HTOLE64 1
#define HAVE_HTOBE16 1
#define HAVE_HTOBE32 1
#define HAVE_HTOBE64 1
#define HAVE_BE64TOH 1
#define HAVE_ALIGNED_ACCESS_REQUIRED 1
#define SIZEOF_SIZE_T 8
#define SIZEOF_WCHAR_T 4
#define _POSIX_C_SOURCE 200809L
#define HAVE_ATTRIBUTE_VISIBILITY_DEFAULT 1
#define HAVE_FUNC_ATTRIBUTE_FORMAT 1
#define HAVE_FUNC_ATTRIBUTE_MALLOC 1
#define HAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL 1
#define HAVE_FUNC_ATTRIBUTE_NORETURN 1
#define HAVE_FUNC_ATTRIBUTE_ALIGNED 1
#define HAVE_WFORMAT_Y2K 1
#define HAVE_C11 1
#define HAVE_C99 1
#define HAVE_MALLOC 1
#define HAVE_REALLOC 1
#define HAVE_STAT_EMPTY_STRING_BUG 1
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
